### ISSUE TITLE
ply export

### ISSUE THREAD

**Issue by komazsofi** [eEcoLiDAR/laserchicken#95] opened 2018-03-13 09:32 UTC
The ply export file cannot be read by Cloud Compare. I got the following error message during the import:

[10:26:57] An error occurred while loading '02gz2_merged_kiv1_kivtest': reading error (no access right?)

My feeling is that Cloud Compare is not able to read the extra scalars, but I am not sure. On user manual http://www.cloudcompare.org/doc/qCC/CloudCompare%20v2.6.1%20-%20User%20manual.pdf page 18 define what kind of ply file is readable with the CC.

Maybe add a csv export which is 100% that readable by CC?

**Comment by cwmeijer** [comment] 2018-03-15 13:10
I can't reproduce the error. Using Cloud Compare I was able to read a ply file that was written with our software. Could you send me an example ply file, that was written with our software and that gives you this error?

**Comment by komazsofi** [comment] 2018-03-19 09:23
e-mail sent with the file

**Comment by cwmeijer** [comment] 2018-03-19 12:31
I still can't reproduce the error. I can load your file without problems in CC. Do you have an error log from Cloud Compare? Other option would be to look at it together, for instance next Wednesday.

**Comment by komazsofi** [comment] 2018-03-19 12:37
Let's see it together on Wednesday.

**Comment by komazsofi** [comment] 2018-03-21 10:38
![cc1](https://user-images.githubusercontent.com/24636311/37705467-6aedf53a-2cfc-11e8-80d1-b92aabf938d6.PNG)

![cc2](https://user-images.githubusercontent.com/24636311/37705475-6e8d74cc-2cfc-11e8-8502-6acd53cbd9b7.PNG)

**Comment by komazsofi** [comment] 2018-03-21 19:27
I have seen that this problem is similar which was reported in several forums in CC>

http://www.danielgm.net/cc/forum/viewtopic.php?t=1138
https://github.com/CloudCompare/CloudCompare/issues/124

**Comment by komazsofi** [comment] 2018-05-08 07:55
If I delete the comment section within the exported ply file CC able to read the without error.

**Comment by cwmeijer** [comment] 2019-11-06 13:59
Long time ago and writing of ply has been changed since then. Closing for now.

**Closed by cwmeijer** 2019-11-06 13:59 UTC
Labels: bug, enhancement, question
